import type { Metadata } from "next"
import { Silkscreen, Unica_One, Kode_Mono } from "next/font/google"
import localFont from "next/font/local"
import Image from "next/image"
import "./globals.css"

const silkscreenFont = Silkscreen({
  weight: "700",
  subsets: ["latin"],
  variable: "--font-silkscreen",
});

const unicaoneFont = Unica_One({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-unicaone",
});

const kodemonoFont = Kode_Mono({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-kodemono",
});

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
})
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode,
}>) {
  return (
    <html lang="en">
    <body>
    {/* Background with gradient and image */}
    <div
      id="this-is-the-background"
      className="relative t-0 size-full"
      style={{
        background: "linear-gradient(180deg, rgba(73,9,200,1) 0%, rgba(46,56,203,1) 35%, rgba(100,134,164,1) 100%)",
      }}
    >
      <Image
        src="/Background.png"
        alt="Photograph of starry night sky"
        width={1440}
        height={2699}
        className="size-full object-cover"
        style={{
          opacity: 0.5, // Adjust opacity to allow gradient visibility
        }}
      />
    </div>

    {/* Content with relative positioning */}
    <div
      className="relative"
      style={{
        position: "fixed",
        top: 80,
        left: 100,
      }}
        >
      {children}
    </div>

    </body>
    </html>
  )
}
