import type { Metadata } from "next"
import { Kode_Mono, Silkscreen, Unica_One } from "next/font/google"
import localFont from "next/font/local"
import Image from "next/image"
import type * as React from "react"
import "./globals.css"

const silkscreenFont = Silkscreen({
  weight: "700",
  subsets: ["latin"],
  variable: "--font-silkscreen",
})

const unicaoneFont = Unica_One({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-unicaone",
})

const kodemonoFont = Kode_Mono({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-kodemono",
})

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
})
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body>
        {/* Background with gradient and image */}
        <div
          id="this-is-the-background"
          className="relative t-0 size-full"
          style={{
            position: "absolute", // Ensures the background moves with the scroll
            top: 0,
            left: 0,
            width: "100%", // Stretches the image width to fit the screen
            height: "auto", // Allows the height to adjust proportionally
            background: "linear-gradient(180deg, rgba(73,9,200,1) 0%, rgba(46,56,203,1) 35%, rgba(100,134,164,1) 100%)",
          }}
        >
          <Image
            src="/Background.png"
            alt="Photograph of starry night sky"
            width={1440}
            height={2699}
            className="size-full object-cover"
            style={{
              width: "100%", // Makes the image fit the device width
              height: "auto", // Keeps the aspect ratio intact
              opacity: 0.5, // Adjust opacity to allow gradient visibility
            }}
          />
        </div>
        {/* Header */}
        <header
          style={{
            display: "flex",
            justifyContent: "space-between",
            alignItems: "center",
            position: "fixed",
            top: 0,
            left: 0,
            width: "100%",
            padding: "10px 20px",
            zIndex: 1000,
          }}
        >
          {/* Logo */}
          <div style={{ width: "100px", height: "auto" }}>
            <Image
              src="/HexLogo.svg"
              alt="DUWIT Hacks Logo"
              width={100}
              height={100}
              style={{ objectFit: "contain" }}
            />
          </div>
        </header>

        {/* MLH Banner */}
        <a
          id="mlh-trust-badge"
          style={{
            display: "block",
            maxWidth: "100px",
            minWidth: "60px",
            position: "fixed",
            right: "50px",
            top: "0",
            width: "10%",
            zIndex: 10000,
          }}
          href="https://mlh.io/eu?utm_source=eu-hackathon&utm_medium=TrustBadge&utm_campaign=2025-season&utm_content=white"
          target="_blank"
          rel="noreferrer"
        >
          <img
            src="https://s3.amazonaws.com/logged-assets/trust-badge/2025/mlh-trust-badge-2025-white.svg"
            alt="Major League Hacking 2025 Hackathon Season"
            style={{ width: "100%" }}
          />
        </a>

        {/* Content */}
        <div
          style={{
            position: "relative",
            zIndex: 1,
          }}
        >
          {children}
        </div>
      </body>
    </html>
  )
}
